package gui;

import javax.mail.Address;
import javax.swing.*;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MessageDisplay {

	private JFrame frmMessageDetails;
	private String subjectText;
	private String[] fromText;
	private String[] toText;
	private String content;
	private String[] cc;
	private JTextField fromContent;
	private JTextField toContent;
	private JTextField ccContent;

	/**
	 * Store all the data
	 */
	
	public MessageDisplay(String inputSubject, Address[] inputSenders, Address[] inputRecipients, Address[] inputCCers, String inputContent) {
		subjectText = inputSubject;
		fromText = new String[inputSenders.length];
		for(int i = 0; i < inputSenders.length; i++)
		{
			fromText[i] = inputSenders[i].toString();
		}

		toText = new String[inputRecipients.length];
		for(int i = 0; i < inputRecipients.length; i++)
		{
			toText[i] = inputRecipients[i].toString();
		}

		if(inputCCers == null)
		{
			cc = new String[1];
			cc[0] = "None";
		}
		else
		{
			cc = new String[inputCCers.length];
			for(int i = 0; i < inputCCers.length; i++)
			{
				cc[i] = inputCCers[i].toString();
			}
		}
		
		content = inputContent;
		
		initialize();
	}

	/**
	 * Create the GUI with the data in
	 * Some of this code is generated by WindowBuilder
	 */
	private void initialize() {
		frmMessageDetails = new JFrame();
		frmMessageDetails.setVisible(true);
		frmMessageDetails.setTitle("Message Details");
		frmMessageDetails.setSize(720,480);
		frmMessageDetails.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		frmMessageDetails.setLocationRelativeTo(null);
		GridBagLayout gridBagLayout = new GridBagLayout();
		gridBagLayout.columnWidths = new int[]{0, 0, 0, 0, 0};
		gridBagLayout.rowHeights = new int[]{0, 0, 0, 0, 0, 0, 0};
		gridBagLayout.columnWeights = new double[]{0.0, 1.0, 0.0, 0.0, Double.MIN_VALUE};
		gridBagLayout.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 1.0, 0.0, Double.MIN_VALUE};
		frmMessageDetails.getContentPane().setLayout(gridBagLayout);
		
		JLabel subject = new JLabel("Subject");
		subject.setText(subjectText);
		subject.setFont(new Font("Tahoma", Font.PLAIN, 16));
		GridBagConstraints gbc_subject = new GridBagConstraints();
		gbc_subject.gridwidth = 4;
		gbc_subject.insets = new Insets(0, 0, 5, 0);
		gbc_subject.gridx = 0;
		gbc_subject.gridy = 0;
		frmMessageDetails.getContentPane().add(subject, gbc_subject);
		
		JLabel from = new JLabel("From:");
		GridBagConstraints gbc_from = new GridBagConstraints();
		gbc_from.anchor = GridBagConstraints.EAST;
		gbc_from.insets = new Insets(0, 5, 5, 5);
		gbc_from.gridx = 0;
		gbc_from.gridy = 1;
		frmMessageDetails.getContentPane().add(from, gbc_from);
		
		fromContent = new JTextField();
		String outputFrom = "";
		//add all addresses to a string to be input into the jtextfield
		for(int i = 0; i < fromText.length; i++)
		{
			if(i == 0)
			{
				outputFrom = fromText[i];
			}
			else
			{
				outputFrom = outputFrom + ", " + fromText[i];
			}
		}
		fromContent.setText(outputFrom);
		fromContent.setEditable(false);
		GridBagConstraints gbc_fromContent = new GridBagConstraints();
		gbc_fromContent.gridwidth = 3;
		gbc_fromContent.insets = new Insets(0, 0, 5, 10);
		gbc_fromContent.fill = GridBagConstraints.HORIZONTAL;
		gbc_fromContent.gridx = 1;
		gbc_fromContent.gridy = 1;
		frmMessageDetails.getContentPane().add(fromContent, gbc_fromContent);
		fromContent.setColumns(10);
		
		JLabel to = new JLabel("To:");
		GridBagConstraints gbc_to = new GridBagConstraints();
		gbc_to.anchor = GridBagConstraints.EAST;
		gbc_to.insets = new Insets(0, 0, 5, 5);
		gbc_to.gridx = 0;
		gbc_to.gridy = 2;
		frmMessageDetails.getContentPane().add(to, gbc_to);
		
		toContent = new JTextField();
		String outputTo = "";
		for(int i = 0; i < toText.length; i++)
		{
			if(i == 0)
			{
				outputTo = toText[i];
			}
			else
			{
				outputTo = outputTo + ", " + toText[i];
			}
		}
		toContent.setText(outputTo);
		toContent.setEditable(false);
		GridBagConstraints gbc_toContent = new GridBagConstraints();
		gbc_toContent.gridwidth = 3;
		gbc_toContent.insets = new Insets(0, 0, 5, 10);
		gbc_toContent.fill = GridBagConstraints.HORIZONTAL;
		gbc_toContent.gridx = 1;
		gbc_toContent.gridy = 2;
		frmMessageDetails.getContentPane().add(toContent, gbc_toContent);
		toContent.setColumns(10);
		
		JLabel lblCc = new JLabel("CC:");
		GridBagConstraints gbc_lblCc = new GridBagConstraints();
		gbc_lblCc.anchor = GridBagConstraints.EAST;
		gbc_lblCc.insets = new Insets(0, 0, 5, 5);
		gbc_lblCc.gridx = 0;
		gbc_lblCc.gridy = 3;
		frmMessageDetails.getContentPane().add(lblCc, gbc_lblCc);
		
		ccContent = new JTextField();
		String outputCC = "";
		for(int i = 0; i < cc.length; i++)
		{
			if(i == 0)
			{
				outputCC = cc[i];
			}
			else
			{
				outputCC = outputCC + ", " + cc[i];
			}
		}
		ccContent.setText(outputCC);
		ccContent.setEditable(false);
		GridBagConstraints gbc_ccContent = new GridBagConstraints();
		gbc_ccContent.insets = new Insets(0, 0, 5, 10);
		gbc_ccContent.gridwidth = 3;
		gbc_ccContent.fill = GridBagConstraints.HORIZONTAL;
		gbc_ccContent.gridx = 1;
		gbc_ccContent.gridy = 3;
		frmMessageDetails.getContentPane().add(ccContent, gbc_ccContent);
		ccContent.setColumns(10);
		
		JScrollPane scrollPane = new JScrollPane();
		GridBagConstraints gbc_scrollPane = new GridBagConstraints();
		gbc_scrollPane.gridwidth = 3;
		gbc_scrollPane.insets = new Insets(0, 0, 10, 10);
		gbc_scrollPane.fill = GridBagConstraints.BOTH;
		gbc_scrollPane.gridx = 1;
		gbc_scrollPane.gridy = 4;
		frmMessageDetails.getContentPane().add(scrollPane, gbc_scrollPane);
		
		JTextArea textArea = new JTextArea();
		textArea.setText(content);
		textArea.setEditable(false);
		textArea.setCaretPosition(0);
		scrollPane.setViewportView(textArea);
		
		JButton btnClose = new JButton("Close");
		GridBagConstraints gbc_btnClose = new GridBagConstraints();
		gbc_btnClose.insets = new Insets(0, 0, 10, 10);
		gbc_btnClose.gridx = 2;
		gbc_btnClose.gridy = 5;
		frmMessageDetails.getContentPane().add(btnClose, gbc_btnClose);
		
		btnClose.addActionListener(new ActionListener()
			{
				public void actionPerformed(ActionEvent e)
				{
					frmMessageDetails.dispose();
				}
			}
		);

	}
}
